# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 6741d41b00ba4c1401829fd59fc2aeb6b2eb447c06807090ce2d94bc48ad23be7313f1d6b114b9b3d024d2c6d8b4b1b0620b1fbfbd68f799c3a3b2174df080c0

test:
  secret_key_base: 473d6775c437b0c3fc8c8a3d84a8d54f74d12d9f3df6ce9fc1bb80e1e1a0b98aeb763d7aeb906cf016babd19cf94031064219339085bd92446a91165bf18776b

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
